### ISSUE TITLE
subset.neuron() doesn't work inside nmapply()

### ISSUE THREAD

**Issue by kjheinz** [natverse/nat#414]
I commonly use `subset.neuron()` inside `nmapply()` in order to apply the same operation to all members of a neuronlist, but following a recent update this no longer seems to work (I am on nat version 1.9.1.9000).

Example:

```r
y5 = read.neurons.catmaid("annotation:NAMK_putative_PAM-y5_RIGHT")
y5.axon.nodes = nlapply(y5, function(x) distal_to(x, node.pointno = x$tags$KJH_dend_cut))
y5.SMP = nmapply(subset, y5, y5.axon.nodes, invert=T)
```
is the code I would have used to subset a group of neurons in the past, but throws the following error:
`Error in eval(e, x$d, parent.frame()) : object 'dots' not found`

I am able to achieve the result I need with the following workaround:
```r
for (i in 1:length(y5)){
  y5.SMP = c(y5.SMP, neuronlist(subset(y5[[i]], y5.axon.nodes[[i]], invert=T)))
}
```

**Comment by jefferis** [comment]
Basically you can either use `prune_vertices` inside `nmapply` *or* apply a function which both calculates the axonal nodes _and_ uses them subset the neuron (using `subset` or `prune_vertices`).

**Comment by kjheinz** [comment]
Thanks @jefferis ! Your final suggestion is particularly intuitive to me, and seems very obvious now that you've pointed it out. I think I originally devised my approach when I was still finding my feet with nat and co, and I've copied it ever since. Thanks for alerting me to these better approaches!

**Comment by jefferis** [comment]
Have decided not to try and fix this as workarounds are better style.
