### ISSUE TITLE
Move features to nat from other packages

### ISSUE THREAD

**Issue by SridharJagannathan** [natverse/nat#423]
Move the following features from:

1) Basic neuron manipulations: https://github.com/natverse/elmr
- [x] Simplify neurons -> https://github.com/natverse/elmr/blob/master/R/simplify_neuron.R
- [x] Stitch neurons -> https://github.com/natverse/elmr/blob/master/R/stitch_neuron.R
- [x] Distal to -> http://natverse.org/elmr/reference/distal_to.html
- [x] prune_twigs http://natverse.org/elmr/reference/prune_twigs.html
2) From registrations: (tbc @jefferis )
- [x] tpsreg -> http://natverse.org/elmr/reference/tpsreg.html
Each feature must be accompanied by relevant test cases (either synthetic or from actual neuron data)

**Comment by SridharJagannathan** [comment]
@jefferis: So far I have finished updating `simplify_neuron` both your and my implementations. As well as `stitch_neurons_mst`, I have also cross-verified the implementation made by @schlegelp and found both the results to be similar. I will continue updating and moving your other `stitch_neurons` and other features as requested. I have made this PR so it is easier for your to review.

**Comment by jefferis** [comment]
Super!

* Is there any difference in the simplify_neuron functionality at present between your version and mine? I didn’t get to review yet. 
* I would bring in the stitch_neuron(s) functions in their current implementations and then switch to your new MST one.
* it would be ideal if we could have a version that works for multiple neurons and a version that stitches a single neuron that has multiple trees. Alternatively there may be a nice way to make a single function that will do either if these.

**Comment by jefferis** [comment]
Closed by #424 972f2db
