### ISSUE TITLE
"pan3d()" not found

### ISSUE THREAD

**Issue by artxz** [natverse/nat#447]
from R console:
`Error in pan3d(2) : could not find function "pan3d"`
However, it works just fine after manually running the function's definition in the console.

**Comment by jefferis** [comment]
Hi @artxz could you give some more details of your setup eg from devtools::session_info() as well as a full reproducible example? Thanks, Greg.

**Comment by artxz** [comment]
Hi @Greg Jefferis <jefferis@gmail.com>

This is not stopping me from doing anything, just a very slight
inconvenience. So if the problem is not reproducible and no one else
complains, then feel free to drop the issue.

If i load natverse and then run

nopen3d()
pan3d(2)


I would get this error

Error in pan3d(2) : could not find function "pan3d"


This is the output of session_info()

> devtools::session_info()
- Session info
------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/New_York
 date     2020-10-27

- Packages
----------------------------------------------------------------------------------------------------------------------------------------------------------
 package            * version    date       lib source

 assertthat           0.2.1      2019-03-21 [1] CRAN (R 4.0.2)

 backports            1.1.10     2020-09-15 [1] CRAN (R 4.0.2)

 callr                3.4.4      2020-09-07 [1] CRAN (R 4.0.2)

 catmaid            * 0.10.0     2020-09-29 [1] Github
(natverse/rcatmaid@0dcbee0)
 checkmate            2.0.0      2020-02-06 [1] CRAN (R 4.0.2)

 cli                  2.0.2      2020-02-28 [1] CRAN (R 4.0.2)

 codetools            0.2-16     2018-12-24 [2] CRAN (R 4.0.2)

 crayon               1.3.4      2017-09-16 [1] CRAN (R 4.0.2)

 crosstalk            1.1.0.1    2020-03-13 [1] CRAN (R 4.0.2)

 dendroextras         0.2.3      2018-01-25 [1] CRAN (R 4.0.2)

 desc                 1.2.0      2018-05-01 [1] CRAN (R 4.0.2)

 devtools             2.3.2      2020-09-18 [1] CRAN (R 4.0.2)

 digest               0.6.25     2020-02-23 [1] CRAN (R 4.0.2)

 dotCall64            1.0-0      2018-07-30 [1] CRAN (R 4.0.2)

 dplyr                1.0.2      2020-08-18 [1] CRAN (R 4.0.2)

 drvid                0.3.0      2020-09-29 [1] Github
(natverse/drvid@867506c)
 ellipsis             0.3.1      2020-05-15 [1] CRAN (R 4.0.2)

 elmr               * 0.6        2020-09-29 [1] Github
(natverse/elmr@d1ec566)
 fansi                0.4.1      2020-01-08 [1] CRAN (R 4.0.2)

 fastmap              1.0.1      2019-10-08 [1] CRAN (R 4.0.2)

 filehash             2.4-2      2019-04-17 [1] CRAN (R 4.0.0)

 fs                   1.5.0      2020-07-31 [1] CRAN (R 4.0.2)

 generics             0.0.2      2018-11-29 [1] CRAN (R 4.0.2)

 glue                 1.4.2      2020-08-27 [1] CRAN (R 4.0.2)

 htmltools            0.5.0      2020-06-16 [1] CRAN (R 4.0.2)

 htmlwidgets          1.5.1      2019-10-08 [1] CRAN (R 4.0.2)

 httpuv               1.5.4      2020-06-06 [1] CRAN (R 4.0.2)

 httr               * 1.4.2      2020-07-20 [1] CRAN (R 4.0.2)

 igraph               1.2.5      2020-03-19 [1] CRAN (R 4.0.2)

 jsonlite             1.7.1      2020-09-07 [1] CRAN (R 4.0.2)

 knitr                1.30       2020-09-22 [1] CRAN (R 4.0.2)

 later                1.1.0.1    2020-06-05 [1] CRAN (R 4.0.2)

 lattice              0.20-41    2020-04-02 [2] CRAN (R 4.0.2)

 lifecycle            0.2.0      2020-03-06 [1] CRAN (R 4.0.2)

 magrittr             1.5        2014-11-22 [1] CRAN (R 4.0.2)

 manipulateWidget     0.10.1     2020-02-24 [1] CRAN (R 4.0.2)

 Matrix               1.2-18     2019-11-27 [2] CRAN (R 4.0.2)

 memoise              1.1.0      2017-04-21 [1] CRAN (R 4.0.2)

 mime                 0.9        2020-02-04 [1] CRAN (R 4.0.0)

 miniUI               0.1.1.1    2018-05-18 [1] CRAN (R 4.0.2)

 nabor                0.5.0      2018-07-11 [1] CRAN (R 4.0.2)

 nat                * 1.10.2     2020-09-29 [1] Github (jefferis/nat@8826cca)

 nat.flybrains      * 1.8.0      2020-09-29 [1] Github
(natverse/nat.flybrains@28ff332)
 nat.nblast         * 1.6.5.9000 2020-09-29 [1] Github
(natverse/nat.nblast@63eb018)
 nat.templatebrains * 1.0        2020-09-29 [1] Github
(jefferislab/nat.templatebrains@6be1fe5)
 nat.utils            0.5.1      2015-07-04 [1] CRAN (R 4.0.2)

 natverse           * 0.2.3      2020-09-29 [1] Github
(natverse/natverse@00fa50c)
 neuprintr          * 1.1        2020-09-29 [1] Github
(natverse/neuprintr@c740a66)
 pillar               1.4.6      2020-07-10 [1] CRAN (R 4.0.2)

 pkgbuild             1.1.0      2020-07-13 [1] CRAN (R 4.0.2)

 pkgconfig            2.0.3      2019-09-22 [1] CRAN (R 4.0.2)

 pkgload              1.1.0      2020-05-29 [1] CRAN (R 4.0.2)

 plyr                 1.8.6      2020-03-03 [1] CRAN (R 4.0.2)

 prettyunits          1.1.1      2020-01-24 [1] CRAN (R 4.0.2)

 processx             3.4.4      2020-09-03 [1] CRAN (R 4.0.2)

 promises             1.1.1      2020-06-09 [1] CRAN (R 4.0.2)

 ps                   1.3.4      2020-08-11 [1] CRAN (R 4.0.2)

 purrr                0.3.4      2020-04-17 [1] CRAN (R 4.0.2)

 R6                   2.4.1      2019-11-12 [1] CRAN (R 4.0.2)

 rappdirs             0.3.1      2016-03-28 [1] CRAN (R 4.0.2)

 Rcpp                 1.0.5      2020-07-06 [1] CRAN (R 4.0.2)

 remotes              2.2.0      2020-07-21 [1] CRAN (R 4.0.2)

 rgl                * 0.100.54   2020-04-14 [1] CRAN (R 4.0.2)

 rlang                0.4.7      2020-07-09 [1] CRAN (R 4.0.2)

 rprojroot            1.3-2      2018-01-03 [1] CRAN (R 4.0.2)

 rstudioapi           0.11       2020-02-07 [1] CRAN (R 4.0.2)

 sessioninfo          1.1.1      2018-11-05 [1] CRAN (R 4.0.2)

 shiny                1.5.0      2020-06-23 [1] CRAN (R 4.0.2)

 spam                 2.5-1      2019-12-12 [1] CRAN (R 4.0.2)

 testthat             2.3.2      2020-03-02 [1] CRAN (R 4.0.2)

 tibble               3.0.3      2020-07-10 [1] CRAN (R 4.0.2)

 tidyselect           1.1.0      2020-05-11 [1] CRAN (R 4.0.2)

 usethis              1.6.3      2020-09-17 [1] CRAN (R 4.0.2)

 vctrs                0.3.4      2020-08-29 [1] CRAN (R 4.0.2)

 webshot              0.5.2      2019-11-22 [1] CRAN (R 4.0.2)

 withr                2.3.0      2020-09-22 [1] CRAN (R 4.0.2)

 xfun                 0.17       2020-09-09 [1] CRAN (R 4.0.2)

 xml2                 1.3.2      2020-04-23 [1] CRAN (R 4.0.2)

 xtable               1.8-4      2019-04-21 [1] CRAN (R 4.0.2)

 yaml                 2.2.1      2020-02-01 [1] CRAN (R 4.0.2)

**Comment by jefferis** [comment]
For some reason the function was never exported. Do you want to try again with latest nat from github and close if all fine.

**Comment by artxz** [comment]
it works now! Thank you!
