### ISSUE TITLE
nTrees in summary

### ISSUE THREAD

**Issue by dokato** [natverse/nat#461]
For convenience, I thought that it'd be nice to have nTrees field in neuronlist summary. I gave it a go with implementation but noticed that some neurons don't have that field, for example:
```
Cell07PNs[[1]]
```

is there a reason for that @jefferis ?

**Comment by jefferis** [comment]
No. Just some old neurons didn't have it when they only had one tree. There is no versioning of the neuron data model I'm afraid. So you would just have to say nTrees=1 when it is missing if you are adding to the summary (which would be great).
