### ISSUE TITLE
Undesired output when stitching with an empty neuronlist

### ISSUE THREAD

**Issue by dokato** [natverse/nat#490]
I try to stitch a single neuron with some of its partners. I use some filter for my selection, so it happens rarely that the partners list is empty. In such case:

```r
> x <- neuronlist()
> nn = Cell07PNs[[1]]
> stitch_neurons(
     c(as.neuronlist(nn), x)
 )
'neuronlist' containing 1 'neuron' object and 'data.frame' with 0 vars [37.4 kB]
```

Despite what docs say:
```
Value: A single neuron object containing all input fragments.
```

Which is weird as calling `c(as.neuronlist(nn), x)` returns correct neuronlist with just a single neuron.

**Comment by jefferis** [comment]
Yes, it looks like that edge case wasn't considered. FWIW `stitch_neurons_mst` is generally recommended – and that seems to work

```
> x <- neuronlist()
> nn = Cell07PNs[1]
> stitch_neurons_mst(c(nn, x))
'neuron' with 180 vertices in 1 tree
```
did you already track down where this goes wrong in `stitch_neurons`?
