### ISSUE TITLE
Need to integrate as.seglist test fix in CRAN release

### ISSUE THREAD

**Issue by jefferis** [natverse/nat#494]
CRAN is still on 1.8 branch
nat may be removed from CRAN by 2022-04-15 unless #492 is ported to https://github.com/natverse/nat/tree/1.8. @dokato I am not sure if you might have the chance to do this?

**Comment by dokato** [comment]
Sure, I'll have a look tomorrow.

**Comment by dokato** [comment]
@jefferis do you want me to make and submit a CRAN build? BTW why don't we push out v `1.10`?

**Comment by jefferis** [comment]
> @jefferis do you want me to make and submit a CRAN build? BTW why don't we push out v `1.10`?

Thank you very much. It would be great if you could test this on the win builder service in addition to the regular GitHub tests. I will need to submit the update — or at least approve it — as the package maintainer.

Yes it would be great if we could submit a 1.10 release but there some changes that I think are likely to cause issues on CRAN (even including the extended vignettes) so I think that's a bigger project.

**Comment by dokato** [comment]
Argh, I rushed a little or rather didn't know that this `win-builder` service can be used independently of cran submission. 
I pushed the updated version of nat 1.8.18 to both.

**Comment by jefferis** [comment]
I think we can close this @dokato ?
